name: Deploy homepage

on:
  push:
    paths:
      - 'homepage.conf'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo in server and reload nginx
        uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /usr/local/src
            git pull origin master
            docker-compose exec homepage service nginx reload
